export const movie_constants = {
  LIST_MOVIES: "LIST_MOVIES_REQUEST",
  LIST_MOVIES_SUCCESS: "LIST_MOVIES_REQUEST_SUCCESS",
  LIST_MOVIES_FAILED: "LIST_MOVIES_REQUEST_FAILED",
  LIST_MOVIES_RESET: "LIST_MOVIES_RESET_REQUEST",

  MOVIE_LIST_RANDOM_RATING: "MOVIE_LIST_RANDOM_RATING_REQUEST",
  MOVIE_LIST_RANDOM_RATING_SUCCESS: "MOVIE_LIST_RANDOM_RATING_SUCCESS",
  MOVIE_LIST_RANDOM_RATING_FAILED: "MOVIE_LIST_RANDOM_RATING_FAILED",
  MOVIE_LIST_RANDOM_RATING_RESET: "MOVIE_LIST_RANDOM_RATING_RESET_REQUEST",

  MOVIE_LIST_ONE_RATING: "MOVIE_LIST_ONE_RATING_REQUEST",
  MOVIE_LIST_ONE_RATING_SUCCESS: "MOVIE_LIST_ONE_RATING_SUCCESS",
  MOVIE_LIST_ONE_RATING_FAILED: "MOVIE_LIST_ONE_RATING_FAILED",
  MOVIE_LIST_ONE_RATING_RESET: "MOVIE_LIST_ONE_RATING_RESET_REQUEST",

  MOVIE_LIST_RATINGS: "MOVIE_LIST_RATINGS_REQUEST",
  MOVIE_LIST_RATINGS_SUCCESS: "MOVIE_LIST_RATINGS_SUCCESS",
  MOVIE_LIST_RATINGS_FAILED: "MOVIE_LIST_RATINGS_FAILED",
  MOVIE_LIST_RATINGS_RESET: "MOVIE_LIST_RATINGS_RESET_REQUEST",
};
