export const user_constants = {
  USER_LOGIN: "USER_LOGIN_REQUEST",
  USER_LOGIN_SUCCESS: "USER_LOGIN_REQUEST_SUCCESS",
  USER_LOGIN_FAILED: "USER_LOGIN_REQUEST_FAILED",
  USER_LOGIN_RESET: "USER_LOGIN_RESET_REQUEST",

  // USER_RESET: "USER_RESET_REQUEST",
  // USER_LOGOUT: "USER_LOGOUT_REQUEST",
};
